apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-collection-publish
  annotations:
    tekton.dev/displayName: Ansible Collection Publish Tekton task
    tekton.dev/pipelines.minVersion: 0.37.4
    tekton.dev/tags: ansible,collection,puiblish
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: Red Hat Community
spec:
  description: Tekton task for publishing ansible collection.
  workspaces:
    - name: source
      description: A workspace that contains fetched git repo with ansible collection code.
  params:
    - name: extra-args
      type: string
      description: "Extra parameters to pass to ansible collection publish"
      default: "-v"
    - name: image
      description: image to use to execute this task
      type: string
      default: "quay.io/ansible/creator-ee:latest"
    - name: collection-path
      description: the path to the ansible collection code
      type: string
  steps:
    - name: ansible-collection-publish
      image: $(params.image)
      env:
        - name: HOME
          value: /tekton/home
      resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        ansible-galaxy collection publish $(params.collection-path) $(params.extra-args)
