apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: antsibull-changelog
  annotations:
    tekton.dev/displayName: Ansible Collection Build Tekton task
    tekton.dev/pipelines.minVersion: 0.37.4
    tekton.dev/tags: ansible,collection,build
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: Red Hat Community
spec:
  description: Tekton task for building ansible collection.
  workspaces:
    - name: source
      description: A workspace that contains fetched git repo with ansible collection code.
  params:
    - name: extra-args
      type: string
      description: "Extra parameters to pass to ansible collection build"
      default: "--verbose"
    - name: image
      description: image to use to execute this task
      type: string
      default: "quay.io/ansible/creator-ee:latest"
    - name: collection-path
      description: the path to the ansible collection code
      type: string
    - name: version
      description: the release version of the ansible collection
      type: string
  steps:
    - name: ansible-collection-build
      image: $(params.image)
      env:
        - name: HOME
          value: /tekton/home
      resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      workingDir: $(workspaces.source.path)/$(params.collection-path)
      script: |
        #!/usr/bin/env sh
        pip install antsibull-changelog
        antsibull-changelog release $(params.extra-args) --version $(params.version)
