apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push-tag
  annotations:
    tekton.dev/pipelines.minVersion: 0.37.4
    tekton.dev/tags: git
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to push the tag in a Git repo.
  params:
    - name: context-directory
      type: string
      description: Context directory within the source repository
      default: "."
    - name: tag
      type: string
      description: The tag to be pushed to git repo
  steps:
    - image: docker.io/alpine/git:v2.26.2
      name: git-push-tag
      env:
        - name: HOME
          value: /tekton/home
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.context-directory)
      script: |
        #!/usr/bin/env sh
        git config --global --add safe.directory $(workspaces.source.path)
        git tag $(params.tag)
        git push origin $(params.tag)
  workspaces:
    - description: The workspace where contains ansible collection code.
      name: source
