apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: ansible-tekton-demo-repo
  namespace: ansible-tekton-demo
spec:
  url: "https://github.com/StinkyBenji/ocp-madness-ansible-collection"
  git_provider:
    secret:
      name: "github-webhook-creds"
      key: "provider.token"
    webhook_secret:
      name: "github-webhook-creds"
      key: "webhook.secret"
