apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    tekton.dev/docker-0: quay.io
    tekton.dev/docker-1: registry.redhat.io
stringData:
  config.json: |
    {your-auth}
type: kubernetes.io/dockerconfigjson
